/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CharityProject } from "./CharityProject";
export * as factories from "./factories";
export { CharityProject__factory } from "./factories/CharityProject__factory";
